### ISSUE TITLE
Add Loader on Login click

### ISSUE THREAD

**Issue by jaydp17** [PleaseDotCom/frontend#250]
On the login page, when the user clicks on the `Login` button after entering credentials, the login button should go into loading state and disabled.

Here's how it should look
<img width="862" alt="screenshot 2018-10-15 at 4 31 28 am" src="https://user-images.githubusercontent.com/1743425/46923292-85b5e500-d033-11e8-92ba-97ec32bbf465.png">

As we use [Semantic UI React](https://react.semantic-ui.com/) their [Button](https://react.semantic-ui.com/elements/button/) component documentation has details on how to set it to loading state and disable it.

**Comment by iRomain** [comment]
Thank you for your contribution @celinrayen !
