### ISSUE TITLE
Add Loader on "My Trips" Page

### ISSUE THREAD

**Issue by jaydp17** [PleaseDotCom/frontend#252]
After login if you go to https://localhost:3000/#/account/trips/all it makes an ajax request to https://staging-api.please.com/trips?include=services and fetches the user's trips.

We need to put a loader over there untill the data loades.
It needs to look something like
<img width="1246" alt="screenshot 2018-10-15 at 4 53 59 am" src="https://user-images.githubusercontent.com/1743425/46923509-6cfafe80-d036-11e8-8c77-4e7c76831d75.png">

_Feel free to add your own improvements_ 😉

As we use [Semantic UI React](https://react.semantic-ui.com/) you can use the [Loader](https://react.semantic-ui.com/elements/loader) component from it.

**Comment by kcoulsy** [comment]
Hey, I could take a look at this / Maybe the other loaders too while I'm at it

**Comment by fcmatteo** [comment]
@kcoulsy That would be great. If you find other places where the loader is missing and want to add them, that would be greatly appreciated.
In the login and register page we already have two open pull requests, so don't worry about those.

If you want to do it, just send the pull request 😉

**Comment by sararahimidarehchi** [comment]
Hi, 
@fcmatteo  I would like to get this fixed as my "Good first issue".
@kcoulsy I have a fix ready for it. Are you still working on this? Or can I open a PR?
