### ISSUE TITLE
Add /cookie-policy static page [Content provided]

### ISSUE THREAD

**Issue by jaydp17** [PleaseDotCom/frontend#253]
Create a static page with the path `/cookie-policy`, along with the default Header & Footer, both header & footer components are readily available.

Please use the content provided over [here](https://s3-eu-west-1.amazonaws.com/please-misc-assets/cookie-policy.html).

You can take inspiration from a static page that we already have https://localhost:3000/#/earn-money

_P.S. you don't have to use the exact markup provided in the [content](https://s3-eu-west-1.amazonaws.com/please-misc-assets/cookie-policy.html)_

**Comment by tom-ando** [comment]
The link to the content is a 403, there's nothing there

**Comment by jaydp17** [comment]
@tom-ando Thanks for letting us know, the link has been updated 🙂

**Comment by kenanchristian** [comment]
hey guys, is this issue still up for grabs? If yes I'm willing to work on it 🙂

**Comment by fcmatteo** [comment]
@kenanchristian sorry, this issue is already done. I just forgot to close it, but you can pick any other. Thanks for your interest!
