### ISSUE TITLE
Fixing Card Size on Search Results

### ISSUE THREAD

**Issue by sarperhorata** [PleaseDotCom/frontend#257]
As can be seen from the image attached, our card (each search result displayed in a card) size is not displayed fixed size. On some services, we display shorter cards due to insufficient data.
We need to have a fixed card size of the following in the given order:

2 rows of title
1 row for review score
2 rows of subtitle (if exists) or description
1 row for price
1 row for location
<img width="665" alt="fixing card size on search" src="https://user-images.githubusercontent.com/21296738/46999845-7ddb6b00-d12f-11e8-8e25-982a598e7d85.png">

**Comment by jhorner32** [comment]
I can take this.

**Comment by jaydp17** [comment]
@jhorner32 I'm really sorry, but I'll have to close this issue as this has been fixed.
There are a few other easy ones in the list of issues, for example https://github.com/PleaseDotCom/frontend/issues/253

I hope you understand.
Thanks for taking interest in the project. Feel free to pick any other issue, and I'll make sure you get all the help required.
