### ISSUE TITLE
Adding Reset Button for Tags on Search Results

### ISSUE THREAD

**Issue by sarperhorata** [PleaseDotCom/frontend#258]
When search is being made by using multiple tags, it'd be helpful if we add a "clear/reset tags" button/link to be shown up right of the tag list on search result filters to efortlessly de-select these tags.
![clear tags](https://user-images.githubusercontent.com/21296738/47000955-1bd03500-d132-11e8-9d4b-651ffdb4a162.png)

**Comment by WebDevRaj** [comment]
I would like to work on this

**Comment by iRomain** [comment]
Thank you @WebDevRaj for your contribution!
