### ISSUE TITLE
Fixing Hover Text Location on Search Results

### ISSUE THREAD

**Issue by sarperhorata** [PleaseDotCom/frontend#262]
For the long named services/trips, names are being displayed within a small textbox, when mouse is hovered over the trip/service name. However, this text is currently being displayed over the images, which looks odd. It should be displayed just over the related text.

<img width="673" alt="show tooltip over the text" src="https://user-images.githubusercontent.com/21296738/47013782-04547480-d151-11e8-9429-29a5f3c3d024.png">

**Comment by giulianovarriale** [comment]
I'm gonna work on this

**Comment by giulianovarriale** [comment]
I am debugging it. Actually, if the text is truncated, the popup is being displayed when mouse is hovered over the card, not only over the truncated text. Should the mouse over the text be the trigger for the popup? Like this ![](http://g.recordit.co/M00odge1L3.gif)

If yes, It is an easy changing.

**Comment by fcmatteo** [comment]
@giulianovarriale The popup should only be visible when the title is truncated and the user hovers on any part of the card. But it should be shown over the title.

**Comment by giulianovarriale** [comment]
Done!

**Comment by iRomain** [comment]
Thanks again @giulianovarriale :)
