### ISSUE TITLE
Fixing Add to Trip Button Behavior

### ISSUE THREAD

**Issue by sarperhorata** [PleaseDotCom/frontend#264]
If you go to a service page (one of the accommodation, activities, food) for example
https://please-master.now.sh/#/services/5bb0e21f93e31066109c16ae
and when clicked on "add to trip", you'll notice that each trip value you clicked will display a day count without hiding the previous trip days.

When a person clicks on a trip, if there is an already displayed trip days, they should be hidden.
Screenshot has been attached for clarification.
<img width="524" alt="add to trip goes crappy" src="https://user-images.githubusercontent.com/21296738/47014278-6d88b780-d152-11e8-9fc2-e20d89652957.png">

**Comment by giulianovarriale** [comment]
Working on this

**Comment by iRomain** [comment]
Thank you for your contribution @giulianovarriale !
