### ISSUE TITLE
Adding Expandible Desciption Field on Service Details Page

### ISSUE THREAD

**Issue by sarperhorata** [PleaseDotCom/frontend#265]
As seen in the screenshot, sometimes we have long service (accommodation, food, activities detail page) descriptions, causing the page looking odd by throwing every functionality to the bottom of the page. 

Considering such cases, if description is longer than 1000 characters, we can show a "more..." link and show the entire text when clicked on it. 

<img width="1204" alt="make it expandible" src="https://user-images.githubusercontent.com/21296738/47015098-c6594f80-d154-11e8-9734-4701ec228058.png">

**Comment by jhalaa** [comment]
Can I work on this issue?
