### ISSUE TITLE
When changing pages on search results, the pins on the map don't change

### ISSUE THREAD

**Issue by iRomain** [PleaseDotCom/frontend#273]
Example:
https://please-master.now.sh/#/results?serviceTypes=food&latitude=51.5073509&longitude=-0.12775829999998223&address=London,%20UK&page=1&limit=10

If you go to page 2 or change the search criteria, the pins on the map don't update

**Comment by tommyka** [comment]
I will take a look at this

**Comment by tommyka** [comment]
Trying to start on this issue but i get *cors* issues when trying to load the data.
Any tips to work around this for local development

**Comment by jaydp17** [comment]
@tommyka can you re-try with `REACT_APP_PARSE_SERVER_URL=https://staging-api.please.com yarn start` ?

**Comment by tommyka** [comment]
Fantastic. im inn

**Comment by iRomain** [comment]
Thank you for your contribution @tommyka !
